sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: koSMSwVsgxioXNsYUbULFqeOwRr8hKrnBIRO2KW2TD721FpXqwoMggjbywCiGmApudaRqZwck3WCOniENT3Rt0C2YPxZYldQN8m/++srP26Mp9cw0JZ7lJdu0a+DF1Q1TG5vFXWvHEu12aUARhFMtpC7B2qHHqLC+A3shIF5HBUgPvltnc0mv+LP2y31g6fdaKvUyTGys8zbWfBcvpCGeRI7n6zi91Z1EZ+7wkbtRLJ4doBkbsCya1QIjBCuZ6r+DLDPJnz4nim2KYMNJ2i1gEBKd19IN7fV4jRIr/hyOsCGtABnmvJEZtuGnaCWRjCE6VBr9D2MYGVmqNfDBTnhMDHxHBK/fk3aO6EBOgI0+/C7TlcEdMk0EPtxBNDm29gApvBAih1/8T8/ezqE4MpaAc5hVKNHP6dYlw+/uzkCRWdeXXKuZQq9ozcdco/y3TN/cFrpf2i8+kKRQ7JzcSgVpMByjV5W+pj0jhWCyv0ZZi3DXsqkKFF7ok+dZLWupxZKDw3ZMY0pEEObLGJilAXW8xgsCdxsTBd7ozK/zzjToVIbA5l3sYdIIzw4esZ/Ce0Y2z17pzp2XDaCS2o9g/YvaGseddoJiipb2bDE4fMjmn95tCVcbTQUKKaevlCag66oj+r5slxd4WsK6AmQV4UcLMxwIOwg7l5N1fv1rdemK3Y=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Home-Lights-and-Shadows_4594
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy